export type Project = {
  id: string;
  name: string;
  category: 'Hospitality' | 'Residential' | 'Commercial';
  location: { vi: string; en: string };
  year: string;
  img: string;
  beforeImg: string;
  gallery: string[];
  description: { vi: string; en: string };
  client: string;
  scale: string;
  services: { vi: string; en: string };
  partner?: string;
  tagline?: { vi: string; en: string };
};

export const allProjects: Project[] = [
  {
    id: "the-marq",
    name: "The Marq",
    category: "Residential",
    location: { vi: "29B Nguyen Dinh Chieu, Da Kao Ward, District 1,TP.HCM", en: "29B Nguyen Dinh Chieu, Da Kao Ward, District 1,HCMC" },
    year: "2023",
    img: "https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%201%20noise%20cleaned-standard.jpg",
    beforeImg: "https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%202%20noise%20cleaned-standard.jpg",
    gallery: ["https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%207%20noise%20cleaned-standard.jpg","https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%2017%20noise%20cleaned-standard.jpg","https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%2018%20noise%20cleaned-standard.jpg","https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%2021%20noise%20cleaned-standard.jpg","https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%2022%20noise%20cleaned-standard.jpg","https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%2023%20noise%20cleaned-standard.jpg","https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%2026%20noise%20cleaned-standard.jpg","https://pepper.builders/assets/projects/themarq_mrs%20Phan/20221017%20-%20The%20Marq%2027%20noise%20cleaned-standard.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "78m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "the-cave",
    name: "The Cave",
    category: "Residential",
    location: { vi: "92 Nguyen Huu Canh Street, Ward 22, TP.HCM", en: "92 Nguyen Huu Canh Street, Ward 22, HCMC" },
    year: "2022",
    img: "https://pepper.builders/assets/projects/The%20Cave/a-57.jpg",
    beforeImg: "https://pepper.builders/assets/projects/The%20Cave/a-57.jpg",
    gallery: ["https://pepper.builders/assets/projects/The%20Cave/a-57.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "205m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "the-nang-suites",
    name: "The Nang Suites",
    category: "Hospitality",
    location: { vi: "Quận Sơn Trà, Đà Nẵng", en: "Son Tra District, Da Nang City" },
    year: "2019",
    img: "https://pepper.builders/assets/projects/the-nang-suites/The-Nang_real.jpg",
    beforeImg: "https://pepper.builders/assets/projects/the-nang-suites/The-Nang_3D_01.jpg",
    gallery: ["https://pepper.builders/assets/projects/the-nang-suites/2.jpg","https://pepper.builders/assets/projects/the-nang-suites/3.jpg","https://pepper.builders/assets/projects/the-nang-suites/4_a-167.jpg","https://pepper.builders/assets/projects/the-nang-suites/5_a-164.jpg","https://pepper.builders/assets/projects/the-nang-suites/6_a-174.jpg","https://pepper.builders/assets/projects/the-nang-suites/7_a-69.jpg","https://pepper.builders/assets/projects/the-nang-suites/8_a-173.jpg","https://pepper.builders/assets/projects/the-nang-suites/9_a-70.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "550 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "chi-bu-riverside-resort",
    name: "Chi-Bu Riverside Resort",
    category: "Hospitality",
    location: { vi: "Thị trấn Nhơn Trạch, Đồng Nai", en: "Nhon Trach Town, Dong Nai Province" },
    year: "2019",
    img: "https://pepper.builders/assets/projects/chi-bu-riverside-cottages/Ch-bu-resort_real.jpg",
    beforeImg: "https://pepper.builders/assets/projects/chi-bu-riverside-cottages/Chi-bu-resort_3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/chi-bu-riverside-cottages/2_a-21.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/3_a-62.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/6_a-84.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/8_a-83.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/11_a-135.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/13_a-144.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/14_a-166.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/16_a-160.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/17_a-158.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/18_a-162.jpg","https://pepper.builders/assets/projects/chi-bu-riverside-cottages/20_a-194.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "2000 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "chi-bu-dorm-and-camp",
    name: "Chi-Bu Dorm and Camp",
    category: "Hospitality",
    location: { vi: "Thị trấn Nhơn Trạch, Đồng Nai", en: "Nhon Trach Town, Dong Nai Province" },
    year: "2019",
    img: "https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/ChiBu-Real-01.jpg",
    beforeImg: "https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/ChiBu-Real-02.jpg",
    gallery: ["https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/2_a.jpg","https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/3_a.jpg","https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/4.jpg","https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/5_a.jpg","https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/6_a.jpg","https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/7_a.jpg","https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/8_a.jpg","https://pepper.builders/assets/projects/chi-bu-dorm-and-camp/9_a.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "10000m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "lucky-palace-apartment",
    name: "Lucky Palace Apartment",
    category: "Residential",
    location: { vi: "Quận 6, TP.HCM", en: "District 6, Ho Chi Minh City" },
    year: "2019",
    img: "https://pepper.builders/assets/projects/lucky-palace-m1/",
    beforeImg: "https://pepper.builders/assets/projects/lucky-palace-m1/01_a-2.jpg",
    gallery: ["https://pepper.builders/assets/projects/lucky-palace-m1/03_a-4.jpg","https://pepper.builders/assets/projects/lucky-palace-m1/04_a-7.jpg","https://pepper.builders/assets/projects/lucky-palace-m1/05_a-37.jpg","https://pepper.builders/assets/projects/lucky-palace-m1/06_a-10.jpg","https://pepper.builders/assets/projects/lucky-palace-m1/07_a-21.jpg","https://pepper.builders/assets/projects/lucky-palace-m1/08_a-28.jpg","https://pepper.builders/assets/projects/lucky-palace-m1/09_a-35.jpg","https://pepper.builders/assets/projects/lucky-palace-m1/10_a-48.jpg","https://pepper.builders/assets/projects/lucky-palace-m1/11_a-50.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "75 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "bare-gallery",
    name: "Bare Gallery",
    category: "Hospitality",
    location: { vi: "Quận 1, TP.HCM", en: "District 1, Ho Chi Minh City" },
    year: "2018",
    img: "https://pepper.builders/assets/projects/bare-gallery/10_a-62.jpg",
    beforeImg: "https://pepper.builders/assets/projects/bare-gallery/Studio-1.jpg",
    gallery: ["https://pepper.builders/assets/projects/bare-gallery/2.jpg","https://pepper.builders/assets/projects/bare-gallery/2_a.jpg","https://pepper.builders/assets/projects/bare-gallery/3.jpg","https://pepper.builders/assets/projects/bare-gallery/5_a-3.jpg","https://pepper.builders/assets/projects/bare-gallery/6_a-12.jpg","https://pepper.builders/assets/projects/bare-gallery/7_a-64.jpg","https://pepper.builders/assets/projects/bare-gallery/9.jpg","https://pepper.builders/assets/projects/bare-gallery/10_a-73.jpg","https://pepper.builders/assets/projects/bare-gallery/11.jpg","https://pepper.builders/assets/projects/bare-gallery/12_a-54.jpg","https://pepper.builders/assets/projects/bare-gallery/13_a-31.jpg","https://pepper.builders/assets/projects/bare-gallery/14_a-28.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "245m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "bare-indochine",
    name: "Bare Indochine",
    category: "Hospitality",
    location: { vi: "Quận 1, TP.HCM", en: "District 1, Ho Chi Minh City" },
    year: "2017",
    img: "https://pepper.builders/assets/projects/bare-indochine/REal.jpg",
    beforeImg: "https://pepper.builders/assets/projects/bare-indochine/3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/bare-indochine/2_a-5.jpg","https://pepper.builders/assets/projects/bare-indochine/3_a-6.jpg","https://pepper.builders/assets/projects/bare-indochine/9_a-20.jpg","https://pepper.builders/assets/projects/bare-indochine/10_a-12.jpg","https://pepper.builders/assets/projects/bare-indochine/11_a-42.jpg","https://pepper.builders/assets/projects/bare-indochine/12_a-24.jpg","https://pepper.builders/assets/projects/bare-indochine/13_a-23.jpg","https://pepper.builders/assets/projects/bare-indochine/17_a-18.jpg","https://pepper.builders/assets/projects/bare-indochine/18_a-11.jpg","https://pepper.builders/assets/projects/bare-indochine/20_a-13.jpg","https://pepper.builders/assets/projects/bare-indochine/22_a-17.jpg","https://pepper.builders/assets/projects/bare-indochine/a-48.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "35m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "pmh-penthouse",
    name: "PMH Penthouse",
    category: "Residential",
    location: { vi: "Quận 7, TP.HCM", en: "District 7, Ho Chi Minh City" },
    year: "2017",
    img: "https://pepper.builders/assets/projects/PMH%20Penthouse/Real.jpg",
    beforeImg: "https://pepper.builders/assets/projects/PMH%20Penthouse/3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/PMH%20Penthouse/2.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/3.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/4.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/4_a.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/5.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/6.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/7.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/8.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/9.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/12.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/13.jpg","https://pepper.builders/assets/projects/PMH%20Penthouse/15.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "400 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "the-park-apartment",
    name: "The Park Apartment",
    category: "Residential",
    location: { vi: "Nha Be Town, TP.HCM", en: "Nha Be Town, Ho Chi Minh City" },
    year: "2017",
    img: "https://pepper.builders/assets/projects/the-park-aparment/1_a-4.jpg",
    beforeImg: "https://pepper.builders/assets/projects/the-park-aparment/05.jpg",
    gallery: ["https://pepper.builders/assets/projects/the-park-aparment/2_a-2.jpg","https://pepper.builders/assets/projects/the-park-aparment/4_a-21.jpg","https://pepper.builders/assets/projects/the-park-aparment/7_a-3.jpg","https://pepper.builders/assets/projects/the-park-aparment/8_a-7.jpg","https://pepper.builders/assets/projects/the-park-aparment/9_a-9.jpg","https://pepper.builders/assets/projects/the-park-aparment/10_a-14.jpg","https://pepper.builders/assets/projects/the-park-aparment/11_a-53.jpg","https://pepper.builders/assets/projects/the-park-aparment/12_a-42.jpg","https://pepper.builders/assets/projects/the-park-aparment/13_a-46.jpg","https://pepper.builders/assets/projects/the-park-aparment/14_a-37.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "75 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "vista-verde-apartment-2",
    name: "Vista Verde Apartment 2",
    category: "Residential",
    location: { vi: "Quận 2, TP.HCM", en: "District 2, Ho Chi Minh City" },
    year: "2017",
    img: "https://pepper.builders/assets/projects/vista-verde-aparment%202/photo.jpg",
    beforeImg: "https://pepper.builders/assets/projects/vista-verde-aparment%202/3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/vista-verde-aparment%202/3_a-16.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/4_a-18.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/5_a-37.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/6_a-25.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/7_a-31.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/8_a-47.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/9_a-38.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/10_a-10.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/11_a-51.jpg","https://pepper.builders/assets/projects/vista-verde-aparment%202/12_a-42.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "45 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "vista-verde-apartment-1",
    name: "Vista Verde Apartment 1",
    category: "Residential",
    location: { vi: "Quận 2, TP.HCM", en: "District 2, Ho Chi Minh City" },
    year: "2017",
    img: "https://pepper.builders/assets/projects/vista-verde-m1/Photos.jpg",
    beforeImg: "https://pepper.builders/assets/projects/vista-verde-m1/3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/vista-verde-m1/2_a-5.jpg","https://pepper.builders/assets/projects/vista-verde-m1/3_a-20.jpg","https://pepper.builders/assets/projects/vista-verde-m1/4_a-6.jpg","https://pepper.builders/assets/projects/vista-verde-m1/5_a-9.jpg","https://pepper.builders/assets/projects/vista-verde-m1/6_a-12.jpg","https://pepper.builders/assets/projects/vista-verde-m1/7_a-24.jpg","https://pepper.builders/assets/projects/vista-verde-m1/8_a-10.jpg","https://pepper.builders/assets/projects/vista-verde-m1/9_a-14.jpg","https://pepper.builders/assets/projects/vista-verde-m1/10_a-26.jpg","https://pepper.builders/assets/projects/vista-verde-m1/11_a-28.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "s. It has a modern design with smooth interiors and open space. Materials and colour palettes are refined. Detailing on the rough cement wall creates the illusion of paint. The space is organised to be youthful and comfortable for the ideal living space for young adults or a small family.",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "wrap-roll",
    name: "Wrap&Roll",
    category: "Commercial",
    location: { vi: "Hai Ba Trung . Huynh Thuc Khang . Taskashimaya . Aeon Mall, Ho Chi Minh city", en: "Hai Ba Trung . Huynh Thuc Khang . Taskashimaya . Aeon Mall, Ho Chi Minh city" },
    year: "2016",
    img: "https://pepper.builders/assets/projects/Wrap_Roll%20/Wrap&Roll_Real.jpg",
    beforeImg: "https://pepper.builders/assets/projects/Wrap_Roll%20/Wrap&Roll_3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/Wrap_Roll%20/1.jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/2.jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/3.jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/4.jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/5.jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/6.jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/7.jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/9.jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/11%20(2).jpg","https://pepper.builders/assets/projects/Wrap_Roll%20/12-(2).jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "150-300m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "acqua-villa",
    name: "Acqua Villa",
    category: "Hospitality",
    location: { vi: "Anh Nguyen Compound, TP. Nha Trang", en: "Anh Nguyen Compound, Nha Trang City" },
    year: "2015",
    img: "https://pepper.builders/assets/projects/acqua-villa/Real.jpg",
    beforeImg: "https://pepper.builders/assets/projects/acqua-villa/3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/acqua-villa/2.JPG","https://pepper.builders/assets/projects/acqua-villa/3.JPG","https://pepper.builders/assets/projects/acqua-villa/4.JPG","https://pepper.builders/assets/projects/acqua-villa/5.jpg","https://pepper.builders/assets/projects/acqua-villa/6.JPG","https://pepper.builders/assets/projects/acqua-villa/7.jpg","https://pepper.builders/assets/projects/acqua-villa/8.jpg","https://pepper.builders/assets/projects/acqua-villa/9.jpg","https://pepper.builders/assets/projects/acqua-villa/10.jpg","https://pepper.builders/assets/projects/acqua-villa/11.jpg","https://pepper.builders/assets/projects/acqua-villa/12.jpg","https://pepper.builders/assets/projects/acqua-villa/13.jpg","https://pepper.builders/assets/projects/acqua-villa/14.jpg","https://pepper.builders/assets/projects/acqua-villa/15.jpg","https://pepper.builders/assets/projects/acqua-villa/16.jpg","https://pepper.builders/assets/projects/acqua-villa/17.JPG","https://pepper.builders/assets/projects/acqua-villa/18.JPG","https://pepper.builders/assets/projects/acqua-villa/19.JPG"],
    description: { vi: '', en: '' },
    client: '',
    scale: "500 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "the-flemington-apartment",
    name: "The Flemington Apartment",
    category: "Residential",
    location: { vi: "Quận 11, TP.HCM", en: "District 11, Ho Chi Minh City" },
    year: "2015",
    img: "https://pepper.builders/assets/projects/the-flemington-m1/1-(2).jpg",
    beforeImg: "https://pepper.builders/assets/projects/the-flemington-m1/3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/the-flemington-m1/2-(2).jpg","https://pepper.builders/assets/projects/the-flemington-m1/3-(2).jpg","https://pepper.builders/assets/projects/the-flemington-m1/4.jpg","https://pepper.builders/assets/projects/the-flemington-m1/5-(2).jpg","https://pepper.builders/assets/projects/the-flemington-m1/6.jpg","https://pepper.builders/assets/projects/the-flemington-m1/7.jpg","https://pepper.builders/assets/projects/the-flemington-m1/8.jpg","https://pepper.builders/assets/projects/the-flemington-m1/9.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "100 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "pepper-house",
    name: "Pepper House",
    category: "Hospitality",
    location: { vi: "Quận 1, TP.HCM", en: "District 1, Ho Chi Minh City" },
    year: "2015",
    img: "https://pepper.builders/assets/projects/pepper-house/Real.jpg",
    beforeImg: "https://pepper.builders/assets/projects/pepper-house/3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/pepper-house/1.jpg","https://pepper.builders/assets/projects/pepper-house/2.jpg","https://pepper.builders/assets/projects/pepper-house/3.jpg","https://pepper.builders/assets/projects/pepper-house/4.jpg","https://pepper.builders/assets/projects/pepper-house/7.jpg","https://pepper.builders/assets/projects/pepper-house/8.jpg","https://pepper.builders/assets/projects/pepper-house/9.jpg","https://pepper.builders/assets/projects/pepper-house/10.jpg","https://pepper.builders/assets/projects/pepper-house/14.jpg","https://pepper.builders/assets/projects/pepper-house/15.jpg","https://pepper.builders/assets/projects/pepper-house/16.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "270 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "tandoor-restaurant",
    name: "Tandoor Restaurant",
    category: "Commercial",
    location: { vi: "Quận 1, TP.HCM", en: "District 1, Ho Chi Minh City" },
    year: "2015",
    img: "https://pepper.builders/assets/projects/tandoor/9.jpg",
    beforeImg: "https://pepper.builders/assets/projects/tandoor/5.jpg",
    gallery: ["https://pepper.builders/assets/projects/tandoor/4.jpg","https://pepper.builders/assets/projects/tandoor/6.jpg","https://pepper.builders/assets/projects/tandoor/7.jpg","https://pepper.builders/assets/projects/tandoor/8.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "300m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "rivera-cove-villa",
    name: "Rivera Cove Villa",
    category: "Residential",
    location: { vi: "Quận 9, TP.HCM", en: "District 9, Ho Chi Minh City" },
    year: "2014",
    img: "https://pepper.builders/assets/projects/rivera-cove-d9/",
    beforeImg: "https://pepper.builders/assets/projects/rivera-cove-d9/2.jpg",
    gallery: ["https://pepper.builders/assets/projects/rivera-cove-d9/3.jpg","https://pepper.builders/assets/projects/rivera-cove-d9/4-(2).jpg","https://pepper.builders/assets/projects/rivera-cove-d9/5.jpg","https://pepper.builders/assets/projects/rivera-cove-d9/6.jpg","https://pepper.builders/assets/projects/rivera-cove-d9/7.jpg","https://pepper.builders/assets/projects/rivera-cove-d9/8.jpg","https://pepper.builders/assets/projects/rivera-cove-d9/9.jpg","https://pepper.builders/assets/projects/rivera-cove-d9/10.jpg","https://pepper.builders/assets/projects/rivera-cove-d9/11.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "500m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "banian-tree-restaurant",
    name: "Banian Tree Restaurant",
    category: "Commercial",
    location: { vi: "Quận 2, TP.HCM", en: "District 2, Ho Chi Minh City" },
    year: "2013",
    img: "https://pepper.builders/assets/projects/banjan-tree/",
    beforeImg: "https://pepper.builders/assets/projects/banjan-tree/2.jpg",
    gallery: ["https://pepper.builders/assets/projects/banjan-tree/3.jpg","https://pepper.builders/assets/projects/banjan-tree/4.jpg","https://pepper.builders/assets/projects/banjan-tree/5.jpg","https://pepper.builders/assets/projects/banjan-tree/6.jpg","https://pepper.builders/assets/projects/banjan-tree/7.jpg","https://pepper.builders/assets/projects/banjan-tree/8.jpg","https://pepper.builders/assets/projects/banjan-tree/9-(2).jpg","https://pepper.builders/assets/projects/banjan-tree/10.jpg","https://pepper.builders/assets/projects/banjan-tree/11-(2).jpg","https://pepper.builders/assets/projects/banjan-tree/12-(2).jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "350 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "chiisana-hashi-restaurant",
    name: "Chiisana Hashi Restaurant",
    category: "Commercial",
    location: { vi: "Quận 2, TP.HCM", en: "District 2, Ho Chi Minh City" },
    year: "2013",
    img: "https://pepper.builders/assets/projects/chiisana-hashi/",
    beforeImg: "https://pepper.builders/assets/projects/chiisana-hashi/1%20(3).jpg",
    gallery: ["https://pepper.builders/assets/projects/chiisana-hashi/2.jpg","https://pepper.builders/assets/projects/chiisana-hashi/3-(2).jpg","https://pepper.builders/assets/projects/chiisana-hashi/4%20(2).jpg","https://pepper.builders/assets/projects/chiisana-hashi/5%20(2).jpg","https://pepper.builders/assets/projects/chiisana-hashi/6%20(2).jpg","https://pepper.builders/assets/projects/chiisana-hashi/7%20(2).jpg","https://pepper.builders/assets/projects/chiisana-hashi/8%20(2).jpg","https://pepper.builders/assets/projects/chiisana-hashi/9-(2).jpg","https://pepper.builders/assets/projects/chiisana-hashi/10%20(2).jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "350 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "elgaucho-steak-house",
    name: "Elgaucho Steak House",
    category: "Commercial",
    location: { vi: "Địa chỉ 1: 19 Nguyễn Siêu, Phường Bến Nghé, Quận 1 Địa chỉ 2: 2 Tây Hồ, Phường Tây Hồ, Hà Nội Địa chỉ 3: 18 Sukhumvit, soi1, Bangkok, Thailand", en: "Địa chỉ 1: 19 Nguyễn Siêu, Phường Bến Nghé, Quận 1 Địa chỉ 2: 2 Tây Hồ, Phường Tây Hồ, Hà Nội Địa chỉ 3: 18 Sukhumvit, soi1, Bangkok, Thailand" },
    year: "2012",
    img: "https://pepper.builders/assets/projects/Elgaucho%20Steak%20House/",
    beforeImg: "https://pepper.builders/assets/projects/Elgaucho%20Steak%20House/",
    gallery: ["https://pepper.builders/assets/projects/Elgaucho%20Steak%20House/"],
    description: { vi: '', en: '' },
    client: '',
    scale: "300m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "bare-hyphen",
    name: "Bare Hyphen",
    category: "Hospitality",
    location: { vi: "Nguyen Dinh Chieu Street, Sai Gon Ward, TP.HCM", en: "Nguyen Dinh Chieu Street, Sai Gon Ward, HCMC" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/Bare%20Hyphen/",
    beforeImg: "https://pepper.builders/assets/projects/Bare%20Hyphen/",
    gallery: ["https://pepper.builders/assets/projects/Bare%20Hyphen/"],
    description: { vi: '', en: '' },
    client: '',
    scale: "230m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "dalcheeni-indian-restaurant",
    name: "Dalcheeni Indian Restaurant",
    category: "Commercial",
    location: { vi: "2A Ngo Van Nam street, District 1, TP.HCM", en: "2A Ngo Van Nam street, District 1, HCMC" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/Dalcheeni%20Indian%20Restaurant/",
    beforeImg: "https://pepper.builders/assets/projects/Dalcheeni%20Indian%20Restaurant/",
    gallery: ["https://pepper.builders/assets/projects/Dalcheeni%20Indian%20Restaurant/"],
    description: { vi: '', en: '' },
    client: '',
    scale: "350m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "the-global-city-1",
    name: "The Global City 1",
    category: "Hospitality",
    location: { vi: "Do Xuan Hop Steet, Binh Trung Ward, TP.HCM", en: "Do Xuan Hop Steet, Binh Trung Ward, HCMC" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/The%20Global%20City%201/_PQT5771-HDR.jpg",
    beforeImg: "https://pepper.builders/assets/projects/The%20Global%20City%201/_PQT5771-HDR.jpg",
    gallery: ["https://pepper.builders/assets/projects/The%20Global%20City%201/_PQT5771-HDR.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "375m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "the-parkland-penthouse",
    name: "The Parkland Penthouse",
    category: "Residential",
    location: { vi: "Vo Nguyen Giap Street, An Khanh Ward, TP.HCM", en: "Vo Nguyen Giap Street, An Khanh Ward, HCMC" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/The%20Parkland%20Penthouse/",
    beforeImg: "https://pepper.builders/assets/projects/The%20Parkland%20Penthouse/",
    gallery: ["https://pepper.builders/assets/projects/The%20Parkland%20Penthouse/"],
    description: { vi: '', en: '' },
    client: '',
    scale: "< Previous project",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "bare-dakao",
    name: "Bare Dakao",
    category: "Hospitality",
    location: { vi: "Nguyen Dinh Chieu street, Phường Sài Gòn, TP.HCM", en: "Nguyen Dinh Chieu street, Saigon Ward, HCMC" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/Bare%20Dakao/",
    beforeImg: "https://pepper.builders/assets/projects/Bare%20Dakao/",
    gallery: ["https://pepper.builders/assets/projects/Bare%20Dakao/"],
    description: { vi: '', en: '' },
    client: '',
    scale: "18m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "bare-chic",
    name: "Bare Chic",
    category: "Hospitality",
    location: { vi: "Quận 1, TP.HCM", en: "District 1, Ho Chi Minh City" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/Bare%20Chic/Bare-Chic_-Real.jpg",
    beforeImg: "https://pepper.builders/assets/projects/Bare%20Chic/Bare%20Chic_3D.jpeg",
    gallery: ["https://pepper.builders/assets/projects/Bare%20Chic/04_a-45.jpg","https://pepper.builders/assets/projects/Bare%20Chic/06_a-11.jpg","https://pepper.builders/assets/projects/Bare%20Chic/07_a-15.jpg","https://pepper.builders/assets/projects/Bare%20Chic/08_a-22.jpg","https://pepper.builders/assets/projects/Bare%20Chic/10_a-19.jpg","https://pepper.builders/assets/projects/Bare%20Chic/11_a-64.jpg","https://pepper.builders/assets/projects/Bare%20Chic/12_a-34.jpg","https://pepper.builders/assets/projects/Bare%20Chic/15_a-67.jpg","https://pepper.builders/assets/projects/Bare%20Chic/17_a-146.jpg","https://pepper.builders/assets/projects/Bare%20Chic/29_a-156.jpg","https://pepper.builders/assets/projects/Bare%20Chic/19_a-147.jpg","https://pepper.builders/assets/projects/Bare%20Chic/20_a-150.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "200 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "kashew-cheese-deli",
    name: "Kashew Cheese Deli",
    category: "Commercial",
    location: { vi: "Quận 2, TP.HCM", en: "District 2, Ho Chi Minh City" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/Kaschew%20deli/Kaschew_real.jpg",
    beforeImg: "https://pepper.builders/assets/projects/Kaschew%20deli/Kaschew_3D.jpg",
    gallery: ["https://pepper.builders/assets/projects/Kaschew%20deli/_DSC8725-low.jpg","https://pepper.builders/assets/projects/Kaschew%20deli/_DSC8728-low.jpg","https://pepper.builders/assets/projects/Kaschew%20deli/_DSC8731-low.jpg","https://pepper.builders/assets/projects/Kaschew%20deli/_DSC8734-low.jpg","https://pepper.builders/assets/projects/Kaschew%20deli/_DSC8735-low.jpg","https://pepper.builders/assets/projects/Kaschew%20deli/_DSC8736-low.jpg","https://pepper.builders/assets/projects/Kaschew%20deli/_DSC8737-low.jpg","https://pepper.builders/assets/projects/Kaschew%20deli/_DSC8740-low.jpg"],
    description: { vi: '', en: '' },
    client: '',
    scale: "55 m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "the-crest-duplex",
    name: "The Crest Duplex",
    category: "Residential",
    location: { vi: "The Metropole Thu Thiem", en: "The Metropole Thu Thiem" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/The%20Crest%20Duplex/",
    beforeImg: "https://pepper.builders/assets/projects/The%20Crest%20Duplex/",
    gallery: ["https://pepper.builders/assets/projects/The%20Crest%20Duplex/"],
    description: { vi: '', en: '' },
    client: '',
    scale: "150m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "bare-tan-dinh",
    name: "Bare Tân Định",
    category: "Hospitality",
    location: { vi: "Tran Khanh Du Street, Phường Sài Gòn, TP.HCM", en: "Tran Khanh Du Street, Saigon Ward, HCMC" },
    year: "2010",
    img: "https://pepper.builders/assets/projects/Bare%20T%C3%A2n%20%C4%90%E1%BB%8Bnh/",
    beforeImg: "https://pepper.builders/assets/projects/Bare%20T%C3%A2n%20%C4%90%E1%BB%8Bnh/",
    gallery: ["https://pepper.builders/assets/projects/Bare%20T%C3%A2n%20%C4%90%E1%BB%8Bnh/"],
    description: { vi: '', en: '' },
    client: '',
    scale: "18m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "the-global-city-2",
    name: "The Global City 2",
    category: "Hospitality",
    location: { vi: "Do Xuan Hop Street, Binh Trung Ward, TP.HCM", en: "Do Xuan Hop Street, Binh Trung Ward, HCMC" },
    year: "2010",
    img: "",
    beforeImg: "",
    gallery: [],
    description: { vi: '', en: '' },
    client: '',
    scale: "375m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "tiny-house",
    name: "Tiny House",
    category: "Hospitality",
    location: { vi: "Nguyen Dinh Chieu Street, Sai Gon Ward, TP.HCM", en: "Nguyen Dinh Chieu Street, Sai Gon Ward, HCMC" },
    year: "2010",
    img: "",
    beforeImg: "",
    gallery: [],
    description: { vi: '', en: '' },
    client: '',
    scale: "18m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  },
  {
    id: "bare-han",
    name: "Bare Han",
    category: "Hospitality",
    location: { vi: "Tran Phu Street, Phường Hải Châu, Đà Nẵng", en: "Tran Phu Street, Hai Chau Ward, Da Nang" },
    year: "2009",
    img: "",
    beforeImg: "",
    gallery: [],
    description: { vi: '', en: '' },
    client: '',
    scale: "270m2",
    services: { vi: 'Thiết kế & Thi công', en: 'Design & Build' },
  }
];
